deploy:
  needs: [build]
  steps: 
    - name: connect with ssh 
      env: 
        PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
        HOST_NAME: ${{ secrets.HOST_NAME }}
        USER_NAME: ${{ secrets.USER_NAME }}
      runs: |
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} '
          cd ./order
          git pull origin master
          npm run start:dev
        '