version: '3.3'
services: 
  mariadb:
    image: mariadb:10
    command: --default-authentication-plugin=mysql_native_password
    container_name: mariaDB
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment: 
      MARIADB_DATABASE: 'order'
      MARIADB_HOST: 'localhost'
      MARIADB_USER: 'root'
      MARIADB_ROOT_PASSWORD: '1234'
      TZ: Asia/Seoul
    ports:
      - '3306:3306'

  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379