version: '3.3'
services: 
  node:
    build: .
    container_name: order
    ports: 
      - "3000:3000"
    expose:
      - "3000"
    links: 
      - mariaDB
    depends_on:
      - mariaDB
  mariaDB:
    image: mariadb:10
    command: --default-authentication-plugin=mysql_native_password
    container_name: mariaDB
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment: 
      MARIADB_DATABASE: 'order'
      MARIADB_HOST: 'localhost'
      MARIADB_USER: 'root'
      MARIADB_ROOT_PASSWORD: '1234'
      TZ: Asia/Seoul
    ports:
      - '3306:3306'
    