on: 
  release:
    types: [created]
  push:
    branches:
    - develop
    - feature/ci-cd
  pull_request:
    branches:
    - develop

name: Deploy DEV API Server to Amazon EC2
jobs:
  deployment:
    runs-on: ubuntu-latest
    name: Deploy to dev environment
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: create env file 
        run: touch .env.dev && echo SECRETS=${{ secrets }} >> .env.dev
      - name: Start dev deploy
        run: npm run start:dev